[project]
name = "gauss-bot"
version = "1.0.0"
description = "Aplicación para resolver sistemas de ecuaciones, realizar cálculos con matrices y vectores, y más."
requires-python = ">=3.12"
dependencies = [
    "customtkinter>=5.2.2",
    "matplotlib>=3.10.3",
    "sympy>=1.14.0",
]

[tool.ruff.format]
skip-magic-trailing-comma = true

[tool.ruff.lint.isort]
case-sensitive = true
combine-as-imports = true
force-sort-within-sections = true
order-by-type = true
relative-imports-order = "closest-to-furthest"
split-on-trailing-comma = false
