[project]
name = "GaussBot"
version = "1.0.0"
description = "Aplicación para resolver cálculos de álgebra lineal."
requires-python = ">=3.12"
dependencies = [
    "bidict>=0.23.1",
    "customtkinter>=5.2.2",
    "matplotlib>=3.10.3",
    "sympy>=1.14.0",
]

[tool.pylint]
disable = ["C0415", "E0401", "R0401", "R0801"]
output-format = "colorized"

[tool.ruff.lint.per-file-ignores]
"src/__init__.py" = ["E402"]
"src/managers/__init__.py" = ["I001"]
"src/utils/__init__.py" = ["I001"]

[tool.ruff.format]
skip-magic-trailing-comma = true

[tool.ruff.lint.isort]
case-sensitive = true
combine-as-imports = true
force-sort-within-sections = true
order-by-type = true
relative-imports-order = "closest-to-furthest"
split-on-trailing-comma = false
